import { NextRequest, NextResponse } from "next/server";
import { readSessionToken, SESSION_COOKIE } from "@/lib/auth";

export function proxy(request: NextRequest) {
  const pathname = request.nextUrl.pathname;
  if (
    pathname === "/login" ||
    pathname === "/register" ||
    pathname === "/admin/login" ||
    pathname.startsWith("/api/auth/") ||
    pathname === "/api/cron/expire-accounts" ||
    pathname === "/api/health"
  ) {
    return NextResponse.next();
  }

  const user = readSessionToken(request.cookies.get(SESSION_COOKIE)?.value);
  if (user) {
    if (pathname.startsWith("/admin") && user.role !== "admin") {
      return NextResponse.redirect(new URL("/", request.url));
    }
    if (pathname.startsWith("/api/admin") && user.role !== "admin") {
      return NextResponse.json({ error: "Forbidden" }, { status: 403 });
    }
    return NextResponse.next();
  }

  if (pathname.startsWith("/api/")) {
    return NextResponse.json(
      { error: "Authentication required" },
      { status: 401, headers: { "Cache-Control": "no-store" } },
    );
  }

  return NextResponse.redirect(
    new URL(
      pathname.startsWith("/admin") ? "/login?next=%2Fadmin" : "/login",
      request.url,
    ),
  );
}

export const config = {
  matcher: [
    // robots.txt / sitemap.xml are generated by the app and must stay public
    "/((?!_next/static|_next/image|favicon.ico|robots\\.txt|sitemap\\.xml|.*\\.(?:svg|png|jpg|jpeg|gif|webp)$).*)",
  ],
};
